name: Python application

on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:18.15.0
    steps:
      - name: Check the container
        run: |
          node --version
          npm -- version
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Test with pytest
        run: |
          export PYTHONPATH=src
          pytest

  Docker-Container:
    runs-on: ubuntu-latest
    container: node:19.8.1
    steps:
      - name: Test the node version
        run: |
          node --version
          npm --version
